// Shared product data for Categories and Product Detail pages
const productsData = [
  {
    id: 1,
    title: "Ground Nuts",
    description:
      "Premium quality ground nuts, carefully selected and processed to maintain their natural freshness and nutritional value.",
    category: "Oilseeds",
    image: "/ground-nuts.png",
    images: ["/ground-nuts.png"],
    rating: 18,
    reviews: 42,
    highlights: [
      "Rich in protein and healthy fats",
      "Freshly harvested and cleaned",
      "Suitable for snacks and cooking",
      "Gluten-free and vegan friendly",
      "Source of essential minerals",
    ],
    features: [
      "Long shelf life due to careful packaging",
      "No artificial preservatives",
      "Sourced from sustainable farms",
      "Ideal for making peanut butter",
      "Low moisture content for better taste",
    ],
    applications:
      "Used in cooking, snacks, peanut butter production, and oil extraction.",
    aboutProduct:
      "Ground Nuts are premium quality oilseeds, rich in protein, healthy fats, and essential minerals. Their natural freshness and versatility make them ideal for snacks, cooking, and oil extraction. They are sourced from sustainable farms and carefully packaged to preserve taste and nutrition. Enjoyed worldwide, ground nuts are a staple in both traditional and modern recipes.",
  },
  {
    id: 2,
    title: "Bold Peanuts",
    description:
      "Premium quality bold peanuts with rich flavor and crunchy texture. Perfect for snacking and cooking.",
    category: "Oilseeds",
    image: "/Bold-Peanuts.png",
    images: ["/Bold-Peanuts.png"],
    rating: 18,
    reviews: 35,
    highlights: [
      "Crunchy texture with rich flavor",
      "High-quality bold peanuts",
      "Great for snacks and recipes",
      "High oil content",
      "Naturally cholesterol free",
    ],
    features: [
      "Uniform size and color",
      "Handpicked for quality",
      "Perfect for roasting and frying",
      "Packed with antioxidants",
      "Non-GMO product",
    ],
    applications: "Ideal for snacking, baking, and confectionery.",
    aboutProduct:
      "Bold Peanuts offer a rich flavor and crunchy texture, handpicked for quality and high oil content. Perfect for snacking, baking, and packed with antioxidants for a healthy treat. These peanuts are non-GMO and uniform in size, making them a favorite for roasting and frying. Their natural goodness supports a healthy lifestyle and culinary creativity.",
  },
  {
    id: 3,
    title: "TJ Peanuts",
    description:
      "Special TJ variety peanuts known for their exceptional taste and nutritional value. Ideal for healthy snacking.",
    category: "Oilseeds",
    image: "/TJ-Peanuts.png",
    images: ["/TJ-Peanuts.png"],
    rating: 32,
    reviews: 51,
    highlights: [
      "Exceptional taste and nutrition",
      "Popular for healthy snacking",
      "Carefully selected TJ variety",
      "Low in saturated fat",
      "Rich in dietary fiber",
    ],
    features: [
      "Ideal for making chikki (peanut brittle)",
      "Consistent crunch in every bite",
      "No added sugar or salt",
      "Suitable for vegan diets",
      "Packed in food-grade material",
    ],
    applications: "Perfect for snacks and health foods.",
    aboutProduct:
      "TJ Peanuts are a special variety known for exceptional taste and high nutritional value. Low in saturated fat and rich in fiber, they are perfect for healthy snacking and traditional sweets. Carefully selected TJ variety ensures consistent crunch and flavor in every bite. Packed in food-grade material, they are suitable for vegan diets and health-conscious consumers.",
  },
  {
    id: 4,
    title: "Java Peanuts",
    description:
      "Imported Java variety peanuts with distinctive flavor profile and smooth texture. Perfect for gourmet recipes.",
    category: "Oilseeds",
    image: "/Java-Peanuts.png",
    images: ["/Java-Peanuts.png"],
    rating: 27,
    reviews: 28,
    highlights: [
      "Distinctive flavor profile",
      "Smooth texture",
      "Ideal for gourmet recipes",
      "Uniform size and shape",
      "High in vitamin E",
    ],
    features: [
      "Preferred by chefs for desserts",
      "Easy to roast and grind",
      "No artificial coloring",
      "Vacuum packed for freshness",
      "Suitable for gluten-free diets",
    ],
    applications: "Used in gourmet and specialty foods.",
    aboutProduct:
      "Java Peanuts feature a distinctive flavor and smooth texture, preferred by chefs for gourmet recipes. High in vitamin E and vacuum packed, they are a premium choice for specialty foods. Their uniform size and easy-to-roast nature make them ideal for desserts and confectionery. Java peanuts are free from artificial coloring and suitable for gluten-free diets.",
  },
  {
    id: 5,
    title: "Roasted Blanch Peanuts",
    description:
      "Carefully roasted and blanched peanuts with a delicate flavor and smooth texture. Great for baking and snacking.",
    category: "Oilseeds",
    image: "/Roasted-Blanch-Peanuts.png",
    images: ["/Roasted-Blanch-Peanuts.png"],
    rating: 21,
    reviews: 19,
    highlights: [
      "Delicate flavor",
      "Smooth texture",
      "Great for baking and snacking",
      "Skinless and easy to digest",
      "Low sodium content",
    ],
    features: [
      "Ready to use in recipes",
      "No added oils or fats",
      "Perfect for trail mixes",
      "Roasted to perfection",
      "Allergen tested",
    ],
    applications: "Ideal for baking and as a snack.",
    aboutProduct:
      "Roasted Blanch Peanuts are delicately roasted and blanched for a smooth, skinless texture. Easy to digest and allergen tested, they are great for baking, snacking, and trail mixes. With no added oils or fats, they are a healthy addition to recipes. Their ready-to-use form saves time in the kitchen and enhances flavor in every dish.",
  },
  {
    id: 6,
    title: "Roasted Split Peanuts",
    description:
      "Split and roasted peanuts with enhanced flavor and aroma. Perfect for garnishing and cooking applications.",
    category: "Oilseeds",
    image: "/Roasted-Split-Peanuts.png",
    images: ["/Roasted-Split-Peanuts.png"],
    rating: 29,
    reviews: 24,
    highlights: [
      "Enhanced flavor and aroma",
      "Perfect for garnishing",
      "Great for cooking",
      "Crispy and crunchy",
      "Rich in plant-based protein",
    ],
    features: [
      "Ideal for Indian chaats",
      "Quick energy source",
      "No trans fats",
      "Sealed for freshness",
      "Easy to sprinkle on dishes",
    ],
    applications: "Used for garnishing and cooking.",
    aboutProduct:
      "Roasted Split Peanuts are split and roasted for enhanced flavor and aroma. Crispy and protein-rich, they are ideal for garnishing, cooking, and quick energy snacks. Sealed for freshness, they are a favorite in Indian chaats and savory dishes. Their plant-based protein content makes them a nutritious choice for all ages.",
  },
  {
    id: 7,
    title: "Coriander seeds",
    description:
      "Coriander seeds are the dried, brown fruits of the coriander plant, Coriandrum sativum. They have a mild, sweet.",
    category: "Spices",
    image: "/Coriander-seed.png",
    images: ["/Coriander-seed.png"],
    rating: 18,
    reviews: 17,
    highlights: [
      "Mild, sweet flavor",
      "Essential spice ingredient",
      "Aromatic and fresh",
      "Rich in antioxidants",
      "Supports digestion",
    ],
    features: [
      "Sun-dried for maximum aroma",
      "No artificial flavors",
      "Used in pickling and curries",
      "Whole and ground options",
      "Packed in resealable bags",
    ],
    applications: "Used in spice blends and cooking.",
    aboutProduct:
      "Coriander seeds are sun-dried for maximum aroma and a mild, sweet flavor. Essential in spice blends and curries, they are rich in antioxidants and support digestion. These seeds are packed in resealable bags to maintain freshness. Used whole or ground, coriander seeds add depth and fragrance to a variety of cuisines.",
  },
  {
    id: 8,
    title: "Fennel seeds",
    description:
      "Fennel seeds are small, elongated, greenish-brown to yellowish-brown seeds with a distinct licorice-like flavor.",
    category: "Spices",
    image: "/fennel.png",
    images: ["/fennel.png"],
    rating: 18,
    reviews: 22,
    highlights: [
      "Distinct licorice-like flavor",
      "Greenish-brown seeds",
      "Popular in spice mixes",
      "Natural breath freshener",
      "Aids in digestion",
    ],
    features: [
      "Can be chewed raw after meals",
      "Used in herbal teas",
      "No added colors",
      "Aromatic and sweet",
      "Rich in dietary fiber",
    ],
    applications: "Used in spice mixes and as a mouth freshener.",
    aboutProduct:
      "Fennel seeds have a distinct licorice-like flavor and are rich in dietary fiber. Used in teas and spice mixes, they aid digestion and serve as a natural breath freshener. Fennel seeds are aromatic and sweet, making them popular after meals. They are also used in herbal teas and traditional remedies for digestive health.",
  },
  {
    id: 9,
    title: "Green millet",
    description:
      "Green millet, also known as bajra or pearl millet, is a small, round, pale yellow to grayish-green grain that thrives in dry, low-water conditions.",
    category: "Other Grains",
    image: "/millet.png",
    images: ["/millet.png"],
    rating: 18,
    reviews: 14,
    highlights: [
      "Thrives in dry conditions",
      "Nutritious grain",
      "Pale yellow to grayish-green",
      "Gluten-free alternative",
      "High in magnesium",
    ],
    features: [
      "Ideal for porridge and flatbreads",
      "Low glycemic index",
      "Sustainably grown",
      "Easy to cook",
      "Rich in antioxidants",
    ],
    applications: "Used in porridge, flatbreads, and animal feed.",
    aboutProduct:
      "Green millet, or bajra, is a nutritious, gluten-free grain high in magnesium and antioxidants. It thrives in dry conditions and is used in porridge, flatbreads, and animal feed. Sustainably grown, green millet is easy to cook and has a low glycemic index. It is valued for its health benefits and versatility in global cuisines.",
  },
  {
    id: 10,
    title: "Cummin Seeds",
    description:
      "Cumin seeds are small, dried fruits (actually schizocarps) of the Cuminum cyminum plant, a member of the parsley family.",
    category: "Spices",
    image: "/cumin-seed.png",
    images: ["/cumin-seed.png"],
    rating: 18,
    reviews: 20,
    highlights: [
      "Aromatic and flavorful",
      "Essential for curries",
      "Small, dried fruits",
      "Boosts immunity",
      "Traditional medicinal use",
    ],
    features: [
      "Hand-cleaned for purity",
      "No added preservatives",
      "Used in spice blends",
      "Enhances flavor of dishes",
      "Rich in iron",
    ],
    applications: "Used in curries and spice blends.",
    aboutProduct:
      "Cummin Seeds are aromatic, flavorful, and rich in iron, essential for curries and spice blends. They boost immunity and are valued for their traditional medicinal uses. Hand-cleaned for purity, cumin seeds enhance the flavor of many dishes. Their unique taste and health benefits make them a staple in kitchens worldwide.",
  },
  {
    id: 11,
    title: "Soyabeans",
    description:
      "Soybeans are a versatile legume, known for their high protein and oil content.",
    category: "Other Grains",
    image: "/soyabean.png",
    images: ["/soyabean.png"],
    rating: 18,
    reviews: 27,
    highlights: [
      "High protein content",
      "Versatile legume",
      "Used for oil extraction",
      "Rich in isoflavones",
      "Cholesterol free",
    ],
    features: [
      "Non-GMO",
      "Used for tofu and soy milk",
      "Essential for vegan diets",
      "Packed with amino acids",
      "Long shelf life",
    ],
    applications: "Used for oil, tofu, and animal feed.",
    aboutProduct:
      "Soyabeans are versatile legumes high in protein and oil, essential for vegan diets. Used for tofu, soy milk, and oil extraction, they offer a long shelf life and health benefits. Non-GMO and packed with amino acids, soybeans are a key ingredient in plant-based diets. They are also used for animal feed and various food products.",
  },
  {
    id: 12,
    title: "Chickpea",
    description:
      "Chickpeas are a versatile and nutritious legume widely consumed worldwide.",
    category: "Pulses",
    image: "/chickpea.png",
    images: ["/chickpea.png"],
    rating: 18,
    reviews: 33,
    highlights: [
      "Nutritious legume",
      "Widely consumed",
      "Versatile in recipes",
      "High in folate",
      "Good source of fiber",
    ],
    features: [
      "Used in hummus and salads",
      "Low in fat",
      "Supports heart health",
      "Easy to cook",
      "Gluten-free",
    ],
    applications: "Used in hummus, salads, and curries.",
    aboutProduct:
      "Chickpeas are nutritious, high in folate and fiber, and support heart health. Widely used in hummus, salads, and curries, they are low in fat and gluten-free. Chickpeas are easy to cook and versatile in both savory and sweet recipes. Their protein and fiber content make them a staple in vegetarian and vegan diets.",
  },
  {
    id: 13,
    title: "Rise",
    description:
      "Rice is a staple food for over half the world's population, particularly in Asia.",
    category: "Pulses",
    image: "/rise.png",
    images: ["/rise.png"],
    rating: 27,
    reviews: 39,
    highlights: [
      "Staple food",
      "Consumed worldwide",
      "Versatile grain",
      "Naturally gluten-free",
      "Easy to digest",
    ],
    features: [
      "Available in multiple varieties",
      "Quick cooking options",
      "Low in fat",
      "Source of energy",
      "Used in sweet and savory dishes",
    ],
    applications: "Used in a variety of dishes globally.",
    aboutProduct:
      "Rice is a staple food, naturally gluten-free and easy to digest, available in many varieties. It is a vital source of energy and used in sweet and savory dishes worldwide. Rice is quick to cook and low in fat, making it suitable for all ages. Its versatility allows it to be enjoyed in countless traditional and modern recipes.",
  },
  {
    id: 14,
    title: "Sesame Seeds",
    description:
      "Sesame seeds are small, oil-rich seeds that are the edible seed of the Sesamum indicum plant.",
    category: "Oilseeds",
    image: "/Sesame.png",
    images: ["/Sesame.png"],
    rating: 27,
    reviews: 25,
    highlights: [
      "Oil-rich seeds",
      "Edible and nutritious",
      "Used in bakery and sweets",
      "Rich in calcium",
      "Contains healthy fats",
    ],
    features: [
      "Cold-pressed for oil extraction",
      "Used in tahini and sweets",
      "Adds crunch to dishes",
      "Natural source of antioxidants",
      "Available in white and black varieties",
    ],
    applications: "Used in bakery, sweets, and oil extraction.",
    aboutProduct:
      "Sesame Seeds are oil-rich, nutritious, and add crunch to bakery and sweets. Rich in calcium and healthy fats, they are cold-pressed for oil and used in many dishes. Available in white and black varieties, sesame seeds are a natural source of antioxidants. They enhance the flavor and texture of both savory and sweet foods.",
  },
];

export default productsData;
